name: git push into personal repo to deploy using vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # SSH 에이전트 설정 및 SSH 키 로드
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GIT_DEPLOY_KEY }}

      # 다른 리포지토리로 푸시
      - name: Push to personal repo
        run: |
          git remote add personal git@github.com:ppyye/sorisonsoon-front.git
          git push personal main
